using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;
using IA.models;

namespace IA.DataBaseContext
{
    public class IAInicializador : System.Data.Entity.DropCreateDatabaseAlways<IAContext>
    {
        protected override void Seed(IAContext context)
        {
            var categorias = new List<Categorias>
            {
                new Categorias{Categoria="sucesos"},
                new Categorias{Categoria="tecnologia"},
                new Categorias{Categoria="deportes"},
                new Categorias{Categoria="economia"},
                new Categorias{Categoria="entretenimiento"},
                new Categorias{Categoria="gastronomia"},
                new Categorias{Categoria="salud"},
                new Categorias{Categoria="religion"}
            };
            categorias.ForEach(s => context.Categorias.Add(s));
            context.SaveChanges();

            var idiomas = new List<Idiomas>
            {
                new Idiomas{Idioma="Español"},
                new Idiomas{Idioma="Ingles"},                
                new Idiomas{Idioma="Aleman"},
                new Idiomas{Idioma="Turco"}
            };
            idiomas.ForEach(s => context.Idiomas.Add(s));
            context.SaveChanges();

            var palabras = new List<Palabras>
            {
                /// SUCESOS - ESPAÑOL
                new Palabras{palabra="asesino",idiomaID=1,categoriaID=1},
                new Palabras{palabra="muerte",idiomaID=1,categoriaID=1},
                new Palabras{palabra="homicidio",idiomaID=1,categoriaID=1},
                new Palabras{palabra="suicidio",idiomaID=1,categoriaID=1},
                new Palabras{palabra="arma",idiomaID=1,categoriaID=1},
                new Palabras{palabra="matar",idiomaID=1,categoriaID=1},
                new Palabras{palabra="muerto",idiomaID=1,categoriaID=1},
                new Palabras{palabra="masacre",idiomaID=1,categoriaID=1},
                new Palabras{palabra="matanza",idiomaID=1,categoriaID=1},
                new Palabras{palabra="moribundo",idiomaID=1,categoriaID=1},
                new Palabras{palabra="deceso",idiomaID=1,categoriaID=1},
                new Palabras{palabra="herido",idiomaID=1,categoriaID=1},
                new Palabras{palabra="heridos",idiomaID=1,categoriaID=1},
                new Palabras{palabra="muertes",idiomaID=1,categoriaID=1},
                new Palabras{palabra="asesinos",idiomaID=1,categoriaID=1},
                new Palabras{palabra="asaltan",idiomaID=1,categoriaID=1},
                new Palabras{palabra="asesinar",idiomaID=1,categoriaID=1},
                new Palabras{palabra="asaltantes",idiomaID=1,categoriaID=1},
                new Palabras{palabra="asaltante",idiomaID=1,categoriaID=1},
                new Palabras{palabra="arma",idiomaID=1,categoriaID=1},
                new Palabras{palabra="armas",idiomaID=1,categoriaID=1},
                new Palabras{palabra="blanca",idiomaID=1,categoriaID=1},
                new Palabras{palabra="ladron",idiomaID=1,categoriaID=1},
                new Palabras{palabra="incidente",idiomaID=1,categoriaID=1},
                new Palabras{palabra="apuñalada",idiomaID=1,categoriaID=1},
                new Palabras{palabra="golpes",idiomaID=1,categoriaID=1},
                new Palabras{palabra="reten",idiomaID=1,categoriaID=1},
                new Palabras{palabra="sospechoso",idiomaID=1,categoriaID=1},
                new Palabras{palabra="sospechosos",idiomaID=1,categoriaID=1},
                new Palabras{palabra="oij",idiomaID=1,categoriaID=1},
                new Palabras{palabra="investigación",idiomaID=1,categoriaID=1},
                new Palabras{palabra="fiscalía",idiomaID=1,categoriaID=1},
                new Palabras{palabra="trasegaba",idiomaID=1,categoriaID=1},
                new Palabras{palabra="drogas",idiomaID=1,categoriaID=1},
                new Palabras{palabra="lavado",idiomaID=1,categoriaID=1},
                new Palabras{palabra="detienen",idiomaID=1,categoriaID=1},
                new Palabras{palabra="abuso",idiomaID=1,categoriaID=1},
                new Palabras{palabra="capturan",idiomaID=1,categoriaID=1},
                new Palabras{palabra="capturado",idiomaID=1,categoriaID=1},
                new Palabras{palabra="detenido",idiomaID=1,categoriaID=1},
                new Palabras{palabra="balazo",idiomaID=1,categoriaID=1},
                new Palabras{palabra="fallecieron",idiomaID=1,categoriaID=1},
                new Palabras{palabra="velocidad",idiomaID=1,categoriaID=1},
                new Palabras{palabra="accidente",idiomaID=1,categoriaID=1},
                new Palabras{palabra="ladrón",idiomaID=1,categoriaID=1},
                new Palabras{palabra="ladrones",idiomaID=1,categoriaID=1},
                new Palabras{palabra="decomisa",idiomaID=1,categoriaID=1},
                new Palabras{palabra="violento",idiomaID=1,categoriaID=1},
                new Palabras{palabra="cocaina",idiomaID=1,categoriaID=1},
                new Palabras{palabra="crack",idiomaID=1,categoriaID=1},
                new Palabras{palabra="oficiales",idiomaID=1,categoriaID=1},
                new Palabras{palabra="oficial",idiomaID=1,categoriaID=1},
                new Palabras{palabra="policias",idiomaID=1,categoriaID=1},
                new Palabras{palabra="policia",idiomaID=1,categoriaID=1},
                new Palabras{palabra="disparos",idiomaID=1,categoriaID=1},
                new Palabras{palabra="disparo",idiomaID=1,categoriaID=1},

                 /// SUCESOS - INGLES
                new Palabras{palabra="murderer",idiomaID=2,categoriaID=1},
                new Palabras{palabra="murder",idiomaID=2,categoriaID=1},
                new Palabras{palabra="homicide",idiomaID=2,categoriaID=1},
                new Palabras{palabra="suicide",idiomaID=2,categoriaID=1},
                new Palabras{palabra="gun",idiomaID=2,categoriaID=1},
                new Palabras{palabra="kill",idiomaID=2,categoriaID=1},
                new Palabras{palabra="dead",idiomaID=2,categoriaID=1},
                new Palabras{palabra="slaughter",idiomaID=2,categoriaID=1},
                new Palabras{palabra="dying",idiomaID=2,categoriaID=1},
                new Palabras{palabra="death",idiomaID=2,categoriaID=1},
                new Palabras{palabra="wounded",idiomaID=2,categoriaID=1},
                new Palabras{palabra="kills",idiomaID=2,categoriaID=1},
                new Palabras{palabra="murderers",idiomaID=2,categoriaID=1},
                new Palabras{palabra="capture",idiomaID=2,categoriaID=1},
                new Palabras{palabra="raiders",idiomaID=2,categoriaID=1},
                new Palabras{palabra="mugger",idiomaID=2,categoriaID=1},
                new Palabras{palabra="arms",idiomaID=2,categoriaID=1},
                new Palabras{palabra="thief",idiomaID=2,categoriaID=1},
                new Palabras{palabra="incident",idiomaID=2,categoriaID=1},
                new Palabras{palabra="blow",idiomaID=2,categoriaID=1},
                new Palabras{palabra="beats",idiomaID=2,categoriaID=1},
                new Palabras{palabra="suspect",idiomaID=2,categoriaID=1},
                new Palabras{palabra="suspects",idiomaID=2,categoriaID=1},
                new Palabras{palabra="alleged",idiomaID=2,categoriaID=1},
                new Palabras{palabra="arsenal",idiomaID=2,categoriaID=1},
                new Palabras{palabra="crushing",idiomaID=2,categoriaID=1},
                new Palabras{palabra="research",idiomaID=2,categoriaID=1},
                new Palabras{palabra="attorney",idiomaID=2,categoriaID=1},
                new Palabras{palabra="hidden",idiomaID=2,categoriaID=1},
                new Palabras{palabra="drug",idiomaID=2,categoriaID=1},
                new Palabras{palabra="fbi",idiomaID=2,categoriaID=1},
                new Palabras{palabra="cia",idiomaID=2,categoriaID=1},
                new Palabras{palabra="wash",idiomaID=2,categoriaID=1},
                new Palabras{palabra="arrested",idiomaID=2,categoriaID=1},
                new Palabras{palabra="abuse",idiomaID=2,categoriaID=1},
                new Palabras{palabra="capture",idiomaID=2,categoriaID=1},
                new Palabras{palabra="captured",idiomaID=2,categoriaID=1},
                new Palabras{palabra="stopped",idiomaID=2,categoriaID=1},
                new Palabras{palabra="suspicious",idiomaID=2,categoriaID=1},
                new Palabras{palabra="died",idiomaID=2,categoriaID=1},
                new Palabras{palabra="excess",idiomaID=2,categoriaID=1},
                new Palabras{palabra="attacked",idiomaID=2,categoriaID=1},
                new Palabras{palabra="attack",idiomaID=2,categoriaID=1},
                new Palabras{palabra="wounds",idiomaID=2,categoriaID=1},
                new Palabras{palabra="calcined",idiomaID=2,categoriaID=1},
                new Palabras{palabra="struck",idiomaID=2,categoriaID=1},
                new Palabras{palabra="hit",idiomaID=2,categoriaID=1},
                new Palabras{palabra="cocaine",idiomaID=2,categoriaID=1},
                new Palabras{palabra="crack",idiomaID=2,categoriaID=1},
                new Palabras{palabra="seize",idiomaID=2,categoriaID=1},
                new Palabras{palabra="gravity",idiomaID=2,categoriaID=1},
                new Palabras{palabra="official",idiomaID=2,categoriaID=1},
                new Palabras{palabra="officials",idiomaID=2,categoriaID=1},
                new Palabras{palabra="police",idiomaID=2,categoriaID=1},
                new Palabras{palabra="assumptions",idiomaID=2,categoriaID=1},
                new Palabras{palabra="shooting",idiomaID=2,categoriaID=1},

                /// SUCESOS - ALEMAN
                new Palabras{palabra="mörder",idiomaID=3,categoriaID=1},
                new Palabras{palabra="homicide",idiomaID=3,categoriaID=1},
                new Palabras{palabra="selbstmord",idiomaID=3,categoriaID=1},
                new Palabras{palabra="suicide",idiomaID=3,categoriaID=1},
                new Palabras{palabra="sie fangen",idiomaID=3,categoriaID=1},
                new Palabras{palabra="mord",idiomaID=3,categoriaID=1},
                new Palabras{palabra="räuber",idiomaID=3,categoriaID=1},
                new Palabras{palabra="waffen",idiomaID=3,categoriaID=1},
                new Palabras{palabra="verdächtigen",idiomaID=3,categoriaID=1},
                new Palabras{palabra="forschung",idiomaID=3,categoriaID=1},
                new Palabras{palabra="gestorben",idiomaID=3,categoriaID=1},
                new Palabras{palabra="zerkleinerung",idiomaID=3,categoriaID=1},
                new Palabras{palabra="rechtsanwalt",idiomaID=3,categoriaID=1},
                new Palabras{palabra="versteckt",idiomaID=3,categoriaID=1},
                new Palabras{palabra="verhaftet",idiomaID=3,categoriaID=1},
                new Palabras{palabra="missbrauch",idiomaID=3,categoriaID=1},
                new Palabras{palabra="gefangen",idiomaID=3,categoriaID=1},
                new Palabras{palabra="angehalten",idiomaID=3,categoriaID=1},
                new Palabras{palabra="er starb",idiomaID=3,categoriaID=1},
                new Palabras{palabra="verletzte",idiomaID=3,categoriaID=1},
                new Palabras{palabra="diebe",idiomaID=3,categoriaID=1},
                new Palabras{palabra="dieb",idiomaID=3,categoriaID=1},
                new Palabras{palabra="ergreifen",idiomaID=3,categoriaID=1},
                new Palabras{palabra="polizei",idiomaID=3,categoriaID=1},
                new Palabras{palabra="gegeben",idiomaID=3,categoriaID=1},
                new Palabras{palabra="knitter",idiomaID=3,categoriaID=1},
                new Palabras{palabra="schwanger",idiomaID=3,categoriaID=1},
                new Palabras{palabra="schießen",idiomaID=3,categoriaID=1},
                new Palabras{palabra="juckreiz",idiomaID=3,categoriaID=1},
                new Palabras{palabra="brennen",idiomaID=3,categoriaID=1},
                new Palabras{palabra="verurteilt",idiomaID=3,categoriaID=1},

                 /// SUCESOS - TURCO
                new Palabras{palabra="ölüm",idiomaID=4,categoriaID=1},
                new Palabras{palabra="öldürme",idiomaID=4,categoriaID=1},
                new Palabras{palabra="İntihar",idiomaID=4,categoriaID=1},
                new Palabras{palabra="orak",idiomaID=4,categoriaID=1},
                new Palabras{palabra="öldür",idiomaID=4,categoriaID=1},
                new Palabras{palabra="ölü",idiomaID=4,categoriaID=1},
                new Palabras{palabra="yaralı",idiomaID=4,categoriaID=1},
                new Palabras{palabra="katiller",idiomaID=4,categoriaID=1},
                new Palabras{palabra="yakalamak",idiomaID=4,categoriaID=1},
                new Palabras{palabra="cinayet",idiomaID=4,categoriaID=1},
                new Palabras{palabra="silah",idiomaID=4,categoriaID=1},
                new Palabras{palabra="beyaz",idiomaID=4,categoriaID=1},
                new Palabras{palabra="hırsız",idiomaID=4,categoriaID=1},
                new Palabras{palabra="olay",idiomaID=4,categoriaID=1},
                new Palabras{palabra="darbe",idiomaID=4,categoriaID=1},
                new Palabras{palabra="şüpheli",idiomaID=4,categoriaID=1},
                new Palabras{palabra="şüpheliler",idiomaID=4,categoriaID=1},
                new Palabras{palabra="İddiası",idiomaID=4,categoriaID=1},
                new Palabras{palabra="katil",idiomaID=4,categoriaID=1},
                new Palabras{palabra="kalp",idiomaID=4,categoriaID=1},
                new Palabras{palabra="kırma",idiomaID=4,categoriaID=1},
                new Palabras{palabra="araştırma",idiomaID=4,categoriaID=1},
                new Palabras{palabra="avukat",idiomaID=4,categoriaID=1},
                new Palabras{palabra="gizli",idiomaID=4,categoriaID=1},
                new Palabras{palabra="uyuşturucu",idiomaID=4,categoriaID=1},
                new Palabras{palabra="yıkama",idiomaID=4,categoriaID=1},
                new Palabras{palabra="tutuklandı",idiomaID=4,categoriaID=1},
                new Palabras{palabra="suistimal",idiomaID=4,categoriaID=1},
                new Palabras{palabra="yakalama",idiomaID=4,categoriaID=1},
                new Palabras{palabra="durduruldu",idiomaID=4,categoriaID=1},
                new Palabras{palabra="şüpheli",idiomaID=4,categoriaID=1},
                new Palabras{palabra="öldü",idiomaID=4,categoriaID=1},
                new Palabras{palabra="fazla",idiomaID=4,categoriaID=1},
                new Palabras{palabra="yaralı",idiomaID=4,categoriaID=1},
                new Palabras{palabra="hırsızlar",idiomaID=4,categoriaID=1},
                new Palabras{palabra="hırsız",idiomaID=4,categoriaID=1},
                new Palabras{palabra="şiddet",idiomaID=4,categoriaID=1},
                new Palabras{palabra="saldırı",idiomaID=4,categoriaID=1},
                new Palabras{palabra="kalsine",idiomaID=4,categoriaID=1},
                new Palabras{palabra="kokain",idiomaID=4,categoriaID=1},
                new Palabras{palabra="oyuncular",idiomaID=4,categoriaID=1},
                new Palabras{palabra="resmi",idiomaID=4,categoriaID=1},
                new Palabras{palabra="polis",idiomaID=4,categoriaID=1},
                new Palabras{palabra="kabuller",idiomaID=4,categoriaID=1},
                new Palabras{palabra="ezilmiş",idiomaID=4,categoriaID=1},
                new Palabras{palabra="hamile",idiomaID=4,categoriaID=1},
                new Palabras{palabra="çekim",idiomaID=4,categoriaID=1},
                new Palabras{palabra="tetik",idiomaID=4,categoriaID=1},
                new Palabras{palabra="kaşınma",idiomaID=4,categoriaID=1},
                new Palabras{palabra="yanık",idiomaID=4,categoriaID=1},
                new Palabras{palabra="mahkum",idiomaID=4,categoriaID=1}

            };
            palabras.ForEach(s => context.Palabras.Add(s));
            context.SaveChanges();
        }
    }
}